In [65]:
#Imports
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
#Create a classifier of type "RandomForest"
clf = RandomForestClassifier(max_depth=80, n_estimators=100)
print('ready')

ready

In [2]:
#Datenerstellung:
iris = datasets.load_iris()
df_target = pd.DataFrame(iris['target'],columns=['Species'])
df_data = pd.DataFrame(iris['data'], columns=iris.feature_names)
df_data = pd.concat([df_data,df_target], axis=1)
print(df_data)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     Species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 5 columns]

In [3]:
#Daten aufbereiten:
X = df_data[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]
y = df_data[['Species']].to_numpy().ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3)

In [66]:
#Trainieren:
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(y_pred)

[1 1 0 0 1 1 1 2 0 2 1 0 1 2 2 0 0 2 2 2 0 0 2 2 2 0 2 2 1 2 1 1 1 0 1 0 0
 2 2 0 2 0 2 2 2]

In [5]:
#Test:
df_result = pd.DataFrame({'predicted':  y_pred,'actual':y_test})
df_result['correct'] = df_result.apply(lambda x: 1 if x['predicted'] == x['actual'] else 0, axis=1)
#Result:
df_result

    predicted  actual  correct
0           1       1        1
1           1       1        1
2           0       0        1
3           0       0        1
4           1       1        1
5           1       1        1
6           1       1        1
7           2       2        1
8           0       0        1
9           2       2        1
10          1       1        1
11          0       0        1
12          1       1        1
13          2       2        1
14          2       2        1
15          0       0        1
16          0       0        1
17          2       2        1
18          2       2        1
19          2       1        0
20          0       0        1
21          0       0        1
22          2       2        1
23          2       2        1
24          2       2        1
25          0       0        1
26          2       2        1
27          2       2        1
28          1       1        1
29          2       2        1
30          1       1        1
31          1       1        1
32          1       1        1
33          0       0        1
34          1       1        1
35          0       0        1
36          0       0        1
37          2       2        1
38          2       2        1
39          0       0        1
40          2       1        0
41          0       0        1
42          2       2        1
43          2       2        1
44          2       2        1

In [67]:
#Accuracy:
print(f"Accuracy: {round(df_result['correct'].sum() / len(df_result) * 100,2)}%")

Accuracy: 95.56%

In [68]:
#Accuracy mit sklearn:
print(f"Accuracy: {round(accuracy_score(y_test,y_pred)*100,2)}%")

Accuracy: 95.56%

In [64]:
#Anwendung des Classifiers:
clf.predict([[6, 3.0, 5.5, 1.8]])

array([2])